---
title       : Coevolving trees and the phylogenetic comparative method
subtitle    : 
author      : Breanna Sipley
job         : PhD, Bioinformatics and Computational Biology
logo        : logo.png
biglog      : logo.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : prettify  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap, mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Models of diversification

<b>MuSSE</b>

- Allow exploration of interactive effects of traits
- Include category such as host-specificity or counterdefense arsenal

Test for interaction btwn chemical defense and conspicuous coloration on diversification. Found chemical defense also increased extinction rate, leading to lower net diversification. Argue escape-and-radiate only includes speciation, neglecting extinction dynamics.

<div style="position: absolute; bottom: 5em; left: 5em; font-weight: bold; color: #fff; font-size: 11px;">
<p style="font-size: 20px"; align="right">Arbuckle & Speed (2015)</p>
</div>

---

## Interpreting simulation model results

- Statistical power determined by replications, and simulations can have high replications (p-val tiny)
- Null hyp known to be false at the outset
- Testing a known-to-be-falses hypothesis is not useful
- Better: comparing magnitude of differences btwn sims
- Suggested: Komolgorov-Smirnov test to compare two distribution generated by data; focus on effect size or test statistic
- ANOVA useful for partitioning variance and calc effects sizes - don't report p-val

<div style="position: absolute; bottom: 5em; left: 5em; font-weight: bold; color: #fff; font-size: 11px;">
<p style="font-size: 20px"; align="right">White et al (2014)</p>
</div>